<?php

/*
 *
 * @author tpay.com
 *
 * Author URI: http://www.tpay.com
 */

$path = plugin_dir_url(__FILE__);
if ((isset($_SERVER['HTTP_X_FORWARDED_PROTO']) || isset($_SERVER['HTTPS']))
    && (($_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' || $_SERVER['HTTPS'] === 'on')) || is_ssl()
) {

    $path = str_replace('http://', 'https://', $path);

}
?>


<script type="text/javascript" src="<?php echo $path ?>../lib/src/common/_js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $path ?>../lib/src/common/_js/jsencrypt.min.js"></script>
<script type="text/javascript" src="<?php echo $path ?>../lib/src/common/_js/string_routines.js"></script>
<script type="text/javascript" src="<?php echo $path ?>../_js/tpayCards.js?26"></script>
<link rel="stylesheet" href="<?php echo $path ?>../lib/src/common/_css/style.css?8">

<input type="hidden" name="carddata" id="carddata" value=""/>
<div class="insidebg">
    <?php echo $this->description; ?>
    <p id="tpayRSA" style="display: none"><?php echo $this->keyRSA; ?></p>
    <div id="powered_by"></div>
    <div id="card_payment">
        <label for="card_number"><?php tpay\Lang::l('card_number') ?></label>
        <input id="card_number" pattern="\d*" autocompletetype="cc-number" size="30" type="tel" autocomplete="off"
               maxlength="23" placeholder="0000 0000 0000 0000" tabindex="1" value=""/>

        <div id="expiry_date_wrapper">
            <label for="transaction_card_expiry_month"><?php tpay\Lang::l('expiration_date') ?></label>
            <input id="expiry_date" maxlength="9" type="tel" placeholder="00 / 00" autocomplete="off"
                   autocompletetype="cc-exp" tabindex="2" value=""/>
        </div>
        <div id="cvc_wrapper">
            <label for="cvc">CVC <span
                    title="<?php tpay\Lang::l('signature') ?>">?</span></label>
            <input id="cvc" maxlength="3" type="tel" autocomplete="off" autocompletetype="cc-cvc" placeholder="000"
                   tabindex="4" value="" pattern=".{3,}"/>
        </div>

        <label for="c_name"><?php tpay\Lang::l('name_on_card') ?></label>

        <input type="text" id="c_name" placeholder="<?php tpay\Lang::l('name_surname') ?>" autocomplete="off"
               name="client_name"
               maxlength="64" tabindex="5" value=""/>

        <label for="c_email">E-mail</label>

        <input type="email" id="c_email" data-formance_algorithm="complex" autocomplete="off" placeholder="E-mail"
               name="client_email" value="" maxlength="64" tabindex="6">
        <input type="hidden" name="tpayID" value="<?php echo $this->midId; ?>">

    </div>

    <div id="card_icons">
        <div class="card_icon" id="visa"></div>
        <div class="card_icon" id="master"></div>
        <div class="card_icon" id="maestro"></div>
        <div class="card_icon" id="diners"></div>
        <div class="card_icon" id="jcb"></div>
    </div>

    <p id="info_msg"></p>


    <div id="loading_scr" style="display:none"><img src="<?php echo $path ?>../lib/src/common/_img/loading.gif"
                                                    style="vertical-align: middle;"/>&nbsp;&nbsp;Processing data,
        please
        wait...
    </div>

</div>
